# Generated by Django 4.2.6 on 2023-10-20 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlogs',
            name='documents',
        ),
        migrations.RemoveField(
            model_name='vlogs',
            name='images',
        ),
        migrations.RemoveField(
            model_name='vlogs',
            name='videos',
        ),
        migrations.AddField(
            model_name='documents',
            name='vlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='main.vlogs'),
        ),
        migrations.AddField(
            model_name='images',
            name='vlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.vlogs'),
        ),
        migrations.AddField(
            model_name='videos',
            name='vlog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='main.vlogs'),
        ),
    ]
