# Generated by Django 4.2.6 on 2023-10-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_vlogs_documents_remove_vlogs_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogs',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
