# Generated by Django 4.2.6 on 2023-10-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_vlogs_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='documents',
            new_name='document',
        ),
        migrations.RemoveField(
            model_name='documents',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='images',
            name='date_uploaded',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='date_uploaded',
        ),
    ]
