# Generated by Django 4.2.6 on 2023-10-21 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_rename_documents_documents_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlogs',
            name='cover',
            field=models.ImageField(null=True, upload_to='uploads/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='vlogs',
            name='tags',
            field=models.CharField(default='life', max_length=50),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vlog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.vlogs')),
            ],
        ),
    ]
