# Generated by Django 4.2.6 on 2023-10-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tags_alter_like_unique_together_alter_vlogs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlogs',
            name='tags',
        ),
        migrations.AddField(
            model_name='vlogs',
            name='tags',
            field=models.ManyToManyField(related_name='vlogs', to='main.tags'),
        ),
    ]
