# Generated by Django 4.2.6 on 2023-10-21 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_vlogs_tags_vlogs_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='likes',
        ),
    ]
