# Generated by Django 4.2.6 on 2023-10-23 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_comments_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vlogs',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
